services:

  swt:
    image: spring-webpack-template:latest
    build: $PWD
    mem_limit: 512m
    restart: unless-stopped
#    ports:
#      - '8080'
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JAVA_OPTS=-Xms256m -Xmx384m -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseCompressedOops
    healthcheck:
      test: [ 'CMD', 'sh', '-c', 'curl -fs localhost:8080/actuator/health | jq .status | grep -q "UP" || exit 1' ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3

  haproxy:
    image: haproxy:alpine
    mem_limit: 128m
    restart: unless-stopped
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      swt:
        condition: service_healthy
    healthcheck:
      test: [ 'CMD', 'sh', '-c', 'pgrep haproxy || exit 1' ]
      start_period: 30s
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - $PWD/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - $PWD/keystore/certs/external.combined.pem:/keystore/external.combined.pem:ro
