filters:
  nonce:
    include:
      - /
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8080
spring:
  application:
    name: spring-webpack-template
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
